In [1]:
import numpy as np
import pandas as pd
from numpy import nan

import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
data_df_1 = pd.read_csv("../../data/training_validation_1.csv")
data_df_2 = pd.read_csv("../../data/training_validation_2.csv")
data_df = pd.concat([data_df_1, data_df_2], axis=0) # Merge data frames


In [3]:
data_df.shape

(39611, 249)

In [4]:
class_0_df = data_df[data_df['class'] == 0]

In [5]:
class_0_df.shape

(25236, 249)

In [6]:
class_0_df.head()

CpuTemperature_vMax  CpuTemperature_vMin  CpuTemperature_vStd  \
0                56.75                44.75             3.523729   
1                48.75                42.25             2.395308   
2                47.50                42.00             2.085815   
3                48.25                42.25             1.853375   
4                50.00                42.50             2.661766   

   CpuTemperature_value  DurationPickToPick_vCnt  DurationPickToPick_vFreq  \
0             47.833333                        0                  0.000000   
1             45.000000                        2                  0.198207   
2             43.825000                        3                  0.296778   
3             45.200000                        3                  0.298541   
4             45.700000                        3                  0.298554   

   DurationPickToPick_vMax  DurationPickToPick_vMin  DurationPickToPick_vStd  \
0                      NaN                      NaN                      NaN   
1                    3.192                    2.807                 0.192500   
2                    3.230                    3.106                 0.051674   
3                    3.307                    3.103                 0.085391   
4                    3.242                    3.153                 0.038577   

   DurationPickToPick_vTrend  ...  VacuumValveClosed_vMin  \
0                        NaN  ...                     NaN   
1                      0.385  ...               -0.715812   
2                      0.020  ...               -0.721671   
3                      0.031  ...               -0.745598   
4                     -0.036  ...               -0.720206   

   VacuumValveClosed_vStd  VacuumValveClosed_vTrend  VacuumValveClosed_value  \
0                     NaN                       NaN                      NaN   
1                0.112918                 -0.013857                -0.580892   
2                0.109421                 -0.008111                -0.596008   
3                0.116748                 -0.002082                -0.595118   
4                0.112639                 -0.001516                -0.615755   

   ValidFrame_vCnt  ValidFrame_vFreq  ValidFrameOptrisPIIRCamera_vCnt  \
0             89.0         11.457455                            259.0   
1            114.0         11.299041                            273.0   
2            114.0         11.277551                            272.0   
3            114.0         11.344572                            271.0   
4            113.0         11.245550                            271.0   

   ValidFrameOptrisPIIRCamera_vFreq  class  run  
0                         27.582899      0    0  
1                         27.058227      0    0  
2                         26.907842      0    0  
3                         26.968238      0    0  
4                         26.969415      0    0  

[5 rows x 249 columns]

In [7]:
from sklearn.cluster import DBSCAN

In [8]:
df = class_0_df.copy()
del df['class']
df = df.fillna(method='backfill')
# X_train = X_train.fillna(-30000)

In [9]:
np.any(np.isnan(df.values)), np.all(np.isfinite(df.values))



(True, False)

In [10]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA

In [11]:
some_df = df.dropna(axis=1)
# del some_df['class']
del some_df['run']

some_df = some_df.filter(regex="vCnt|value")
some_df.shape



(25236, 59)

In [12]:
X_train = StandardScaler().fit_transform(some_df.values)
# X_train = MinMaxScaler().fit_transform(some_df.values)
X_train

array([[ -0.50448497,  -5.55964688,  -4.91055701, ...,  -2.99215467,
        -10.95534263,  -2.52225859],
       [ -0.96554986,  -1.94758683,  -0.05566187, ...,  -1.43896199,
          0.16464061,   0.52123944],
       [ -1.15675618,  -0.1415568 ,  -0.05566187, ...,  -0.60262747,
          0.16464061,   0.30384672],
       ...,
       [  1.61776962,  -3.75361685,  -1.67396025, ...,   1.78689972,
          0.16464061,   0.08645401],
       [  1.47131371,  -5.55964688,  -4.91055701, ...,  -2.99215467,
          0.16464061,  -0.13093871],
       [  1.98390939,  -5.55964688,  -4.91055701, ...,  -2.99215467,
         -0.28015872,  -0.13093871]])

In [13]:
%%time
model = DBSCAN().fit(X_train)
len(set(model.labels_))

Wall time: 2min 32s


1

In [14]:
# X_train = StandardScaler().fit_transform(some_df.values)
X_train = MinMaxScaler().fit_transform(some_df.values)
X_train

array([[0.23877443, 0.        , 0.        , ..., 0.        , 0.56296296,
        0.59021407],
       [0.14896989, 0.5       , 0.75      , ..., 0.15853659, 0.74814815,
        0.63302752],
       [0.11172742, 0.75      , 0.75      , ..., 0.24390244, 0.74814815,
        0.62996942],
       ...,
       [0.65213946, 0.25      , 0.5       , ..., 0.48780488, 0.74814815,
        0.62691131],
       [0.62361331, 0.        , 0.        , ..., 0.        , 0.74814815,
        0.62385321],
       [0.72345483, 0.        , 0.        , ..., 0.        , 0.74074074,
        0.62385321]])

In [15]:
%%time
model = DBSCAN().fit(X_train)
len(set(model.labels_))

Wall time: 2min 35s


97

In [16]:
X_train = StandardScaler().fit_transform(some_df.values)
# X_train = MinMaxScaler().fit_transform(some_df.values)
X_train

array([[ -0.50448497,  -5.55964688,  -4.91055701, ...,  -2.99215467,
        -10.95534263,  -2.52225859],
       [ -0.96554986,  -1.94758683,  -0.05566187, ...,  -1.43896199,
          0.16464061,   0.52123944],
       [ -1.15675618,  -0.1415568 ,  -0.05566187, ...,  -0.60262747,
          0.16464061,   0.30384672],
       ...,
       [  1.61776962,  -3.75361685,  -1.67396025, ...,   1.78689972,
          0.16464061,   0.08645401],
       [  1.47131371,  -5.55964688,  -4.91055701, ...,  -2.99215467,
          0.16464061,  -0.13093871],
       [  1.98390939,  -5.55964688,  -4.91055701, ...,  -2.99215467,
         -0.28015872,  -0.13093871]])

In [17]:
X_train = PCA(n_components=0.95).fit_transform(X_train)
X_train.shape

(25236, 24)

In [18]:
%%time
model = DBSCAN().fit(X_train)
len(set(model.labels_))

Wall time: 12.1 s


1

In [19]:
# X_train = StandardScaler().fit_transform(some_df.values)
X_train = MinMaxScaler().fit_transform(some_df.values)
X_train

array([[0.23877443, 0.        , 0.        , ..., 0.        , 0.56296296,
        0.59021407],
       [0.14896989, 0.5       , 0.75      , ..., 0.15853659, 0.74814815,
        0.63302752],
       [0.11172742, 0.75      , 0.75      , ..., 0.24390244, 0.74814815,
        0.62996942],
       ...,
       [0.65213946, 0.25      , 0.5       , ..., 0.48780488, 0.74814815,
        0.62691131],
       [0.62361331, 0.        , 0.        , ..., 0.        , 0.74814815,
        0.62385321],
       [0.72345483, 0.        , 0.        , ..., 0.        , 0.74074074,
        0.62385321]])

In [20]:
X_train = PCA(n_components=0.99).fit_transform(X_train)
X_train.shape

(25236, 30)

In [21]:
%%time
model = DBSCAN().fit(X_train)
len(set(model.labels_))

Wall time: 50.4 s


92

In [ ]:
fig = plt.figure(figsize=(15,10))
ax = fig.add_subplot(projection='3d')

# ax.scatter(X_train[:,0], X_train[:,1], X_train[:,2])

for label in set(model.labels_):
    ax.scatter(X_train[model.labels_==label,0], X_train[model.labels_==label,1], X_train[model.labels_==label,2])
